name: Set TV Configuration
on:
  workflow_dispatch:
    inputs:
      setting_file:
        required: true
        description: The Settings to apply to the target TV
        type: choice
        options:
          - Menu
          - Calendar
          - Baseball/Registration
          - Basketball/Registration
          - Soccer/Registration
          - FlagFootball/Registration
          - Volleyball/Registration
          - TestConfiguration
      target_tv:
        required: true
        description: The TV to change
        type: choice
        options:
          - TV1
          - TV2
          - TV3
          - TV4
          - TestTV

permissions:
  repository-projects: write

jobs:
  set-tv-configuration:
    runs-on: ubuntu-latest

    env:
      SETTINGS_FILE: ${{ inputs.setting_file }}
      TARGET_TV: ${{ inputs.target_tv }}

    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            Settings
            StantonCityPark

      - name: Copy Settings to TV
        run: |
          cp ${GITHUB_WORKSPACE}/Settings/$SETTINGS_FILE/Settings.json ${GITHUB_WORKSPACE}/StantonCityPark/ConcessionStand/$TARGET_TV/Settings.json

      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -a
          git commit -m "Copied $SETTINGS_FILE to $TARGET_TV"
          git push