name: Set TV Configuration
on:
  workflow_dispatch:
    inputs:
      setting_file:
        required: true
        description: The Settings to apply to the target TV
        type: choice
        options:
          - Menu/RegularMenu
          - Menu/TournamentMenu
          - Calendar/WeekView
          - External/IgniteAthletics
          - OutOfSchoolBash/Current
          - OutOfSchoolBash/Postponed
          - Leagues/Baseball/SpringRegistrationStartingSoon
          - Leagues/Baseball/FallRegistrationStartingSoon
          - Leagues/Baseball/RegistrationGoingOnNow
          - Leagues/Baseball/WelcomeToRegistration
          - Leagues/Basketball/Registration
          - Leagues/Soccer/SpringRegistrationStartingSoon
          - Leagues/Soccer/SummerRegistrationStartingSoon
          - Leagues/Soccer/FallRegistrationStartingSoon
          - Leagues/Soccer/RegistrationGoingOnNow
          - Leagues/Soccer/WelcomeToRegistration
          - Leagues/Softball/Registration
          - Leagues/FlagFootball/Registration
          - Leagues/Volleyball/Registration
          - Leagues/Combo/FallRegistrationStartingSoon

      target_tv:
        required: true
        description: The TV to change
        type: choice
        options:
          - TV1
          - TV2
          - TV3
          - TV4

jobs:
  set-tv-configuration:
    runs-on: ubuntu-latest

    permissions:
      repository-projects: write
      contents: write

    env:
      SETTINGS_FILE: ${{ inputs.setting_file }}
      TARGET_TV: ${{ inputs.target_tv }}

    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            Settings
            StantonCityPark

      - name: Copy $SETTINGS_FILE to $TARGET_TV
        run: |
          cp ${GITHUB_WORKSPACE}/Settings/$SETTINGS_FILE/Settings.json ${GITHUB_WORKSPACE}/StantonCityPark/ConcessionStand/$TARGET_TV/Settings.json

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ${GITHUB_WORKSPACE}/StantonCityPark/ConcessionStand/$TARGET_TV/Settings.json
          git commit -m "Copied $SETTINGS_FILE to $TARGET_TV"
          git push